In [10]:
import numpy as np
#создание матрицы
matrix = np.zeros((40, 40))
matrix2 = np.zeros((40, 40))
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
#произвольное заполнение матрицы
import random
for i in range(40):
    for j in range(40):
        matrix[i][j] = round(random.random())
print(matrix)

[[1. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 1. 1. 0.]
 ...
 [1. 0. 1. ... 0. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 [0. 1. 1. ... 0. 0. 1.]]


In [13]:
%matplotlib
import matplotlib.pyplot as plt
plt.ion()
for z in range(100): 
    for i in range(40):
        for j in range(40):
            #граничащие клетки
            if i == 0: # для первой строки
                if j == 0:#угловая клетка слева сверху
                    if matrix[i][j] == 0:
                        if (matrix[i+1][j] == 1) and (matrix[i+1][j+1] == 1) and (matrix[i][j+1] == 1):
                            matrix2[i][j] = 1
                    else: 
                        kol = 0
                        if matrix[i+1][j] == 1:
                            kol += 1
                        if matrix[i+1][j+1] == 1:
                            kol += 1
                        if matrix[i][j+1] == 1:
                            kol += 1
                        if kol == 2 or kol == 3:
                            matrix2[i][j] = 1
                        kol = 0
                if j == 39: #угловая клетка справа сверху
                    if matrix[i][j] == 0:
                        if (matrix[i][j-1] == 1) and (matrix[i+1][j-1] == 1) and (matrix[i+1][j] == 1):
                            matrix2[i][j] = 1
                    else:
                        kol = 0
                        if matrix[i][j-1] == 1:
                            kol += 1
                        if matrix[i+1][j-1] == 1:
                            kol += 1
                        if matrix[i+1][j] == 1:
                            kol += 1
                        if kol == 2 or kol == 3:
                            matrix2[i][j] = 1 
                        kol = 0
                if j != 0 and j != 39: #для первого ряда без угловых
                    kol = 0
                    if matrix[i][j-1] == 1:
                        kol += 1
                    if matrix[i][j+1] == 1:
                        kol += 1
                    if matrix[i+1][j-1] == 1:
                        kol += 1
                    if matrix[i+1][j] == 1:
                        kol += 1
                    if matrix[i+1][j+1] == 1:
                        kol += 1
                    if (matrix[i][j] == 0) and (kol == 3):
                        matrix2[i][j] = 1
                    if (matrix[i][j] == 1) and ((kol == 2) or (kol ==3)):
                        matrix2[i][j] = 1
                    kol = 0
            if i == 39: #для последней строки
                if j == 0:#угловая клетка слева снизу
                    if matrix[i][j] == 0:
                        if (matrix[i-1][j] == 1) and (matrix[i-1][j+1] == 1) and (matrix[i][j+1] == 1):
                            matrix2[i][j] = 1
                    else: 
                        kol = 0
                        if matrix[i-1][j] == 1:
                            kol += 1
                        if matrix[i-1][j+1] == 1:
                            kol += 1
                        if matrix[i][j+1] == 1:
                            kol += 1
                        if kol == 2 or kol == 3:
                            matrix2[i][j] = 1
                        kol = 0
                if j == 39: #угловая клетка справа снизу
                    if matrix[i][j] == 0:
                        if (matrix[i][j-1] == 1) and (matrix[i-1][j-1] == 1) and (matrix[i-1][j] == 1):
                            matrix2[i][j] = 1
                    else:
                        kol = 0
                        if matrix[i][j-1] == 1:
                            kol += 1
                        if matrix[i-1][j-1] == 1:
                            kol += 1
                        if matrix[i-1][j] == 1:
                            kol += 1
                        if kol == 2 or kol == 3:
                            matrix2[i][j] = 1 
                        kol = 0
                if j != 0 and j != 39: #для последнего ряда без угловых
                    kol = 0
                    if matrix[i][j-1] == 1:
                        kol += 1
                    if matrix[i][j+1] == 1:
                        kol += 1
                    if matrix[i-1][j-1] == 1:
                        kol += 1
                    if matrix[i-1][j] == 1:
                        kol += 1
                    if matrix[i-1][j+1] == 1:
                        kol += 1
                    if (matrix[i][j] == 0) and (kol == 3):
                        matrix2[i][j] = 1
                    if (matrix[i][j] == 1) and ((kol == 2) or (kol ==3)):
                        matrix2[i][j] = 1
                    kol = 0           
            if j == 0 and i != 0 and i != 39: #для первого столбца без угловых
                kol = 0
                if matrix[i-1][j] == 1:
                    kol += 1
                if matrix[i-1][j+1] == 1:
                    kol += 1
                if matrix[i][j+1] == 1:
                    kol += 1
                if matrix[i+1][j] == 1:
                    kol += 1
                if matrix[i+1][j+1] == 1:
                    kol += 1
                if (matrix[i][j] == 0) and (kol == 3):
                    matrix2[i][j] = 1
                if (matrix[i][j] == 1) and ((kol == 2) or (kol == 3)):
                    matrix2[i][j] = 1
                kol = 0
            if j == 39 and i != 0 and i != 39: #для последнего столбца без угловых
                kol = 0
                if matrix[i-1][j-1] == 1:
                    kol += 1
                if matrix[i-1][j] == 1:
                    kol += 1
                if matrix[i][j-1] == 1:
                    kol += 1
                if matrix[i+1][j-1] == 1:
                    kol += 1
                if matrix[i+1][j] == 1:
                    kol += 1
                if (matrix[i][j] == 0) and (kol == 3):
                    matrix2[i][j] = 1
                if (matrix[i][j] == 1) and ((kol == 2) or (kol == 3)):
                    matrix2[i][j] = 1
                kol = 0
            if i != 0 and j !=0 and i != 39 and j != 39:
                kol = 0
                if matrix[i-1][j-1] == 1:
                    kol += 1
                if matrix[i-1][j] == 1:
                    kol += 1
                if matrix[i-1][j+1] == 1:
                    kol += 1
                if matrix[i][j-1] == 1:
                    kol += 1
                if matrix[i][j+1] == 1:
                    kol += 1
                if matrix[i+1][j-1] == 1:
                    kol += 1
                if matrix[i+1][j] == 1:
                    kol += 1
                if matrix[i+1][j+1] == 1:
                    kol += 1
                if (matrix[i][j] == 0) and (kol == 3):
                    matrix2[i][j] = 1
                if (matrix[i][j] == 1) and ((kol == 2) or (kol == 3)):
                    matrix2[i][j] = 1
                kol = 0
    plt.pcolormesh(matrix, cmap='winter', edgecolors="k", shading='flat') 
    plt.axis('off')
    plt.draw()
    plt.pause(0.1)
    matrix = matrix2  
    matrix2 = np.zeros((40, 40))
plt.ioff()
plt.show()

Using matplotlib backend: Qt5Agg
